swagger: '2.0'
info:
  version: "1"
  title: "polypandaApi Documentation"
  description: polypandaApi is the api documentation for polypanda api service
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: "dev.polypanda.io:8080"
basePath: /api/v1
schemes:
 - http

consumes:
- application/json
produces:
- application/json

paths:
  /panda:
    x-summary: panada Collection
    get:
      summary: return panda objects
      parameters:
        - name: pageNum
          in: query
          description: page of pandas to return
          type: integer
      responses:
        200:
          description: response ok
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/NotFound'

definitions:
  RetSimple:
    title: RetSimple
    type: object
    properties:
      status:
        type : string
      message:
        type: string
      extra:
        type: string
  RetPanda:
    title: RetPanda
    type: object
    properties:
      status:
        type : string
      message:
        type: string
      extra:
        type: string
      pandas:
        type: array
        items:
          $ref: '#/definitions/Panda'
    required:
      - status
      - message
    example:
      status: "OK"
      message: ""
      extra: ""
      pandas:
        - pandaIndex: 0
          genes: "MDhmZTQxMTRlMDlkYTkyODJjY2Q4ZjY0NDExYTRiNTI="
          birthTime: 1523031825
          coolDown: 1800
          rank: 0
          motherID: 0
          fatherID: 0
          generation: 0
          owner: "NGUyODI4MGIwZTZhNDA1ZjU0MjI="
          ownerName: "divine-frog"
          photoURL: "localofphoto"
          snapURL:
        - pandaIndex: 1
          genes: "MjQ1NjRmNzZmMjcxMGQxMDI2MWE2N2FlNTc3MGUxNzc="
          birthTime: 1523031825
          coolDown: 172800
          rank: 0
          motherID: 0
          fatherID: 0
          generation: 0
          owner: "NjQyOTZlM2IyNDM0MTAyNDFlMjY="
          ownerName: "frosty-butterfly"
          photoURL: "localofphoto"
          snapURL:
    
  Panda:
    title: Panda
    type: object
    properties:
      pandaIndex:
        type: integer
      genes:
        type: string
      birthTime:
        type: integer
      coolDown:
        type: integer 
      rank:
        type: integer
      motherID:
        type: integer
      fatherID:
        type: integer
      generation:
        type: integer
      owner:
        type: string
      ownerName:
        type: string
      photoURL:
        type: string
      snapURL:
        type: string
    example:
      pandaIndex: 0
      genes: "MDhmZTQxMTRlMDlkYTkyODJjY2Q4ZjY0NDExYTRiNTI="
      birthTime: 1523031825
      coolDown: 1800
      rank: 0
      motherID: 0
      fatherID: 0
      generation: 0
      owner: "NGUyODI4MGIwZTZhNDA1ZjU0MjI="
      ownerName: "divine-frog"
      photoURL: "localofphoto"
      snapURL:
    
  
 # Descriptions of common responses
responses:
  NotFound:
    description: The specified resource was not found
    schema:
      $ref: "#/definitions/RetSimple"
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: "#/definitions/RetSimple"
