swagger: '2.0'
info:
  version: '1.0'
  title: "polypandaApi Documentation"
  description: polypandaApi is the api documentation for polypanda api service
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: dev.polypanda.io
basePath: /api/v1
schemes:
- http
consumes:
- application/json
produces:
- application/json

paths:
  /panda/all:
    x-summary: panada Collection
    get:
      summary: return all panda objects; however, the number of returns is limited to maxRecords defined in app.conf
      responses:
        200:
          description: response ok
          schema:
            $ref: '#/components/definitions/RetPanda'
          examples:
            $ref: '#/components/examples/pandaExample'
            
        401:
          $ref: '#/components/responses/Unauthorized'
        404:
          $ref: '#/components/responses/NotFound' 
          
# Descriptions of common components
components:
  definitions:
    RetSimple:
      title: RetSimple
      type: object
      properties:
        status:
          type : string
        message:
          type: string
        extra:
          type: string
    RetPanda:
      title: RetPanda
      type: object
      properties:
        status:
          type : string
        message:
          type: string
        extra:
          type: string
        pandas:
          type: array
          items:
            $ref: '#/components/definitions/Panda'
      
    Panda:
      title: Panda
      type: object
      properties:
        pandaIndex:
          type: int
        genes:
          type: string
        birthTime:
          type: long
        coolDown:
          type: long 
        rank:
          type: int
        motherID:
          type: int
        fatherID:
          type: int
        generation:
          type: int
        owner:
          type: string
        ownerName:
          type: string
        photoURL:
          type: string
        snapURL:
          type: string
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    # Schema for error response body
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
  examples:
    pandaExample:
      application/json:
        status: "OK"
        message: ""
        extra: ""
        pandas:
          - pandaIndex: 0
            genes: "MDhmZTQxMTRlMDlkYTkyODJjY2Q4ZjY0NDExYTRiNTI="
            birthTime: 1523031825
            coolDown: 1800
            rank: 0
            motherID: 0
            fatherID: 0
            generation: 0
            owner: "NGUyODI4MGIwZTZhNDA1ZjU0MjI="
            ownerName: "divine-frog"
            photoURL: "localofphoto"
            snapURL:
          - pandaIndex: 1
            genes: "MjQ1NjRmNzZmMjcxMGQxMDI2MWE2N2FlNTc3MGUxNzc="
            birthTime: 1523031825
            coolDown: 172800
            rank: 0
            motherID: 0
            fatherID: 0
            generation: 0
            owner: "NjQyOTZlM2IyNDM0MTAyNDFlMjY="
            ownerName: "frosty-butterfly"
            photoURL: "localofphoto"
            snapURL:
  

      
     
      
      
